name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install
        run: |
          sudo gem install bundler jekyll
          sudo bundle install

      - name: Clean
        run: |
          if [ -d "docs" ]; then
            rm -rf docs/*
          fi

      - name: Build
        run: bundle exec jekyll build -d docs
